sudo: required
services:
  - docker

before_install: 
  - docker build -t ccollinsibe/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true ccollinsibe/docker-react npm run test

deploy:
  provider: elasticbeanstalk 
  region: "eu-north-1"
  app: "test-beanstalk"
  env: "Test-beanstalk-env"
  bucket_name: "elasticbeanstalk-eu-north-1-722758629684"
  bucket_path: "test-beanstalk"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"